# Generated by Django 4.2.28 on 2026-04-16 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('fire', 'Fire'), ('medical', 'Medical Emergency'), ('violence', 'Violence/Conflict'), ('stampede', 'Stampede Risk'), ('suspicious', 'Suspicious Activity'), ('lost_person', 'Lost Person'), ('technical', 'Technical/Infrastructure Failure')], max_length=20, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='Accuracy radius in meters', null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('responding', 'Responding'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm'), ('duplicate', 'Duplicate Report'), ('rejected', 'Rejected'), ('closed', 'Closed/Archived')], default='pending', max_length=20)),
                ('confidence_score', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='events.event')),
                ('parent_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_reports', to='monitoring.incident')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='Accuracy radius in meters', null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sos_type', models.CharField(choices=[('panic', 'Panic / General Help'), ('medical', 'Medical Emergency'), ('threat', 'Security Threat'), ('trapped', 'Trapped / Crowded'), ('unknown', 'Unknown / Silent')], default='panic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active Emergency'), ('assigned', 'Assigned to Responder'), ('en_route', 'Responder En Route'), ('arrived', 'Responder Arrived'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('critical', 'Critical')], default='critical', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'High Danger'), ('emergency', 'Critical Emergency')], default='info', max_length=20)),
                ('audience_type', models.CharField(choices=[('all', 'All Attendees'), ('volunteers', 'Volunteers Only'), ('zone', 'Specific Zone')], default='all', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_meters', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_alerts', to='events.event')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.incident')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy / Assisting'), ('responding', 'En Route to SOS'), ('patrolling', 'On Patrol'), ('offline', 'Offline')], default='available', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_locations', to='events.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='responder_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('sos', 'SOS Alert'), ('incident', 'Incident Report'), ('assignment', 'Volunteer Assignment'), ('broadcast', 'Safety Broadcast'), ('system', 'System Action')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('assigned', 'Assigned'), ('status_change', 'Status Changed'), ('priority_change', 'Priority Changed'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('marked_false', 'Marked False')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.incident')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CrowdLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('source_type', models.CharField(choices=[('ticket_scan', 'Ticket Scan'), ('live_tracking', 'Live Tracking')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_locations', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SOSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('reported', 'Reported'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.sosalert')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sos_alert', 'timestamp'], name='monitoring__sos_ale_b40ad7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['event', 'status'], name='monitoring__event_i_aa4985_idx'),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['created_at'], name='monitoring__created_4dcef2_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyalert',
            index=models.Index(fields=['event', 'is_active'], name='monitoring__event_i_018fab_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyalert',
            index=models.Index(fields=['created_at'], name='monitoring__created_62e594_idx'),
        ),
        migrations.AddIndex(
            model_name='responderlocation',
            index=models.Index(fields=['event', 'status'], name='monitoring__event_i_3091dd_idx'),
        ),
        migrations.AddIndex(
            model_name='responderlocation',
            index=models.Index(fields=['user', 'event'], name='monitoring__user_id_d9a490_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='monitoring__user_id_13fc75_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='monitoring__created_b498e4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='monitoring__expires_19d18e_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['incident', 'timestamp'], name='monitoring__inciden_931d03_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['event', 'status'], name='monitoring__event_i_099dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['priority'], name='monitoring__priorit_49dc48_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='monitoring__created_5218eb_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_active'], name='monitoring__is_acti_cb35e4_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdlocation',
            index=models.Index(fields=['event', 'timestamp'], name='monitoring__event_i_4f919c_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='monitoring__latitud_ebcde2_idx'),
        ),
    ]
