# Generated by Django 4.2.16 on 2026-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_add_location_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned to Responder'), ('in_progress', 'Help In Progress'), ('completed', 'Completed'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20),
        ),
    ]
