# Generated by Django 4.2.28 on 2026-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_sosalert_completed_at_alter_sosalert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Has the organizer/admin acknowledged this SOS alert'),
        ),
    ]
