# Generated by Django 4.2.28 on 2026-02-05 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_attendance',
            field=models.PositiveIntegerField(default=0, help_text='Real-time check-in count'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('SCANNED', 'Scanned'), ('INVALIDATED', 'Invalidated')], default='ISSUED', max_length=20)),
                ('scan_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
