# Generated by Django 4.2.28 on 2026-02-06 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_current_attendance_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('source', models.CharField(choices=[('SCAN', 'Ticket Scan'), ('LIVE', 'Live Tracking'), ('MANUAL', 'Manual Log')], default='LIVE', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_locations', to='core.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'timestamp'], name='core_crowdl_event_i_2e109d_idx'), models.Index(fields=['lat', 'lng'], name='core_crowdl_lat_153feb_idx')],
            },
        ),
    ]
