# Generated by Django 4.2.28 on 2026-02-06 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sosalert_incident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='title',
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('FIRE', 'Fire'), ('MEDICAL', 'Medical Emergency'), ('VIOLENCE', 'Violence/Conflict'), ('STAMPEDE', 'Stampede Risk'), ('SUSPICIOUS', 'Suspicious Activity'), ('LOST_PERSON', 'Lost Person'), ('TECH_FAILURE', 'Technical/Infra Failure'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['event', 'severity'], name='core_incide_event_i_ebc45f_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['event', 'status'], name='core_incide_event_i_86213b_idx'),
        ),
    ]
