# Generated by Django 4.2.28 on 2026-02-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_incident_title_incident_assigned_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosalert',
            name='is_active',
        ),
        migrations.AddField(
            model_name='sosalert',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('CRITICAL', 'Critical')], default='CRITICAL', max_length=10),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='sos_type',
            field=models.CharField(choices=[('PANIC', 'Panic / Distress'), ('MEDICAL', 'Medical Emergency'), ('THREAT', 'Security Threat'), ('TRAPPED', 'Trapped/Crowd Crush'), ('UNKNOWN', 'Unknown Emergency')], default='PANIC', max_length=20),
        ),
        migrations.AddField(
            model_name='sosalert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sosalert',
            index=models.Index(fields=['event', 'status'], name='core_sosale_event_i_345fca_idx'),
        ),
    ]
