# Generated by Django 4.2.28 on 2026-02-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sosalert_is_active_sosalert_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('EMERGENCY', 'Critical Emergency')], default='INFO', max_length=15)),
                ('audience_type', models.CharField(choices=[('ALL', 'All Attendees'), ('VOLUNTEERS', 'Volunteers Only'), ('ZONE', 'Specific Zone')], default='ALL', max_length=15)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_alerts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_alerts', to='core.event')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status'], name='core_safety_event_i_a629ab_idx'), models.Index(fields=['created_at'], name='core_safety_created_4687b6_idx')],
            },
        ),
    ]
