# Generated by Django 4.2.28 on 2026-02-06 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_safetyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('RESPONDING', 'Responding'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_positions', to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status'], name='core_respon_event_i_93eb8b_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
