# Generated by Django 4.2.28 on 2026-02-06 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_incidentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_action_logs', to=settings.AUTH_USER_MODEL)),
                ('sos_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.sosalert')),
            ],
            options={
                'indexes': [models.Index(fields=['sos_alert', 'timestamp'], name='core_soslog_sos_ale_83374e_idx')],
            },
        ),
    ]
